=== gustavo-bertoldi/BRP_ETIC/code/XMLfiles/reglesProjet.dtd
<!ELEMENT projet (nomProjet?, typeMarche?, typeConstruction?, typeLot?, site?, datePrixRef?, coeffAdapt?, chapitre*)>
<!ELEMENT chapitre (intitule, categorie*)>
<!ELEMENT categorie (intitule, famille*)>
<!ELEMENT famille (intitule, sousFamille*)>
<!ELEMENT sousFamille (intitule, descriptif*)>
<!ELEMENT descriptif (nomDescriptif, description, courteDescription, descriptif*, ligneChiffrage*)>
<!ELEMENT ligneChiffrage (unite, localisation, quantite, prixUnitaire)>
<!ELEMENT nomProjet (#PCDATA)>
<!ELEMENT typeMarche (#PCDATA)>
<!ELEMENT typeConstruction (#PCDATA)>
<!ELEMENT typeLot (#PCDATA)>
<!ELEMENT site (#PCDATA)>
<!ELEMENT datePrixRef (#PCDATA)>
<!ELEMENT coeffAdapt (#PCDATA)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT nomDescriptif (#PCDATA)>
<!ELEMENT description ANY>
<!ELEMENT courteDescription (#PCDATA)>
<!ELEMENT unite (#PCDATA)>
<!ELEMENT prixUnitaire (#PCDATA)>
<!ELEMENT localisation (#PCDATA)>
<!ELEMENT quantite (#PCDATA)>
<!ELEMENT b ANY>
<!ELEMENT i ANY>
<!ELEMENT u ANY>
<!ELEMENT ul (li+)>
<!ELEMENT li ANY>
<!ATTLIST projet idProjet CDATA #REQUIRED>
<!ATTLIST chapitre idChapitre CDATA #REQUIRED>
<!ATTLIST categorie idCategorie CDATA #REQUIRED>
<!ATTLIST famille idFamille CDATA #REQUIRED>
<!ATTLIST sousFamille idSousFamille CDATA #REQUIRED>
<!ATTLIST descriptif idDescriptif CDATA #REQUIRED>
<!ATTLIST descriptif type CDATA #REQUIRED>
<!ATTLIST ligneChiffrage idLigneChiffrage CDATA #REQUIRED>

=== gustavo-bertoldi/BRP_ETIC/code/BRP_front_end/src/main/webapp/XMLfiles/1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE projet SYSTEM "reglesProjet.dtd">
<projet idProjet="1">
    <nextId>4</nextId>
    <lot id="_1" intitule="hello">
        <titre1 id="_2" intitule="ee">
            <descriptif id="_3" idBD="04_ETA_03_01_001" type="ouvrage">
                <nomDescriptif>Membrane d’étanchéité TPO</nomDescriptif>
                <description/>
                <courteDescription/>
                <unite>m2</unite>
                <ligneChiffrage idLigneChiffrage="1">
                    <localisation>iuhraaa</localisation>
                    <quantite>1.0</quantite>
                    <prixUnitaire>17.0</prixUnitaire>
                </ligneChiffrage>
                <ligneChiffrage idLigneChiffrage="2">
                    <localisation/>
                    <quantite>1.0</quantite>
                    <prixUnitaire>17.0</prixUnitaire>
                </ligneChiffrage>
            </descriptif>
        </titre1>
    </lot>
</projet>
